### Gaussian Elimination Tutorial 


<style>
    .blue {
        background-color: #0074D9;
    }
</style>

<div class="blue">
 In order to learn about the algorithm in the best way, we will follow an example story in the context of drug discovery (Story by Chatgpt!)
</div>


### Unraveling the Formula: A Computational Journey in Drug Discovery

There are 4 potential compounds that show promise in treating a deadly disease named NEUROX. We  have to figure out the precise proportion of each excipient to create an effective and safe drug formula. Having too much or too little of each compound can cause problems with toxicty, poor efficacy and the list goes on!  

 




not to worry, our scientists have conducted a series of experiments where they kept all but one excipient constant to see the effects of the change in efficacy and toxicity. 


<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

<p>The system of equations representing the experiments is given by:</p>

\[
\begin{align*}
2C_1 + 3C_2 + 1.5C_3 + 0.5C_4 &= E_1 \\
1C_1 + 2C_2 + 2.5C_3 + 1.5C_4 &= E_2 \\
2.5C_1 + 1C_2 + 3C_3 + 2C_4 &= E_3 \\
1.5C_1 + 2.5C_2 + 1C_3 + 3C_4  &= E_4 \\
\end{align*}
\]


After some exploring, the team has realised it might be best solved computationally using **Gaussian Elimination**. Gaussian Elimination is a robust method for soliving systems of linear equations. The equations are systematically manipulated to reduce the system to a form that can be easily solved for the concentration of each excipient compound.

<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

Before we jump into code, let's have a look at how Gauss Elimination is carried out mathematically!
* you have the following equations:


\[
\begin{align*}
eqn 1 = 2x + y -z = 3 \\
eqn 2 = x +y + 5z = 6 \\
eqn3 = -x +3y -2z = 3 \\
\end{align*}
\]

step 1: Elimination step - reduce the system of equations so that the unknown x is removed from the last 2 equations - how do we do this? We keep eqn 1 constant as it is in a good position for our *PIVOT*. In your pivot you want to avoid zeros and the largest number per column should be swapped for the pivot. 

Lets get rid of **X** - our pivot here is eqn1 (2x is larger than x and -x!)

we will multiply eqn2 by a factor of 2 to give:

\[
\begin{align*}
eqn 2  = 2x +2y + 10z = 6 \\
\end{align*}
\]

and then take  eqn 2* from eqn 1 to give:

\[
\begin{align*}
eqn 2  = eqn1 - 2(eqn2) \\
eqn 2 = y -11z = -9
\end{align*}
\]

we now do the same thing for equation 3 in the x column! this time we have to multiply by -2 in order to get a positive +2x in the column so that when we do the formula it wil zero! hence our factor is -2!

\[
\begin{align*}
eqn3 = -x +3y -2z = 3 \\
eqn3 = eqn1 - (-2)(eqn3) \\
eqn3 = 7y -5 7 = 9
\end{align*}
\]


<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>


Take your new equations and the next step is to remove *Y*! Have a go at moving onto the *Y* column and picking a *PIVOT* (hint you shouldn't have zero numbers and every other *Y* has to be multiplied to match it)!

the final resulting equations are:

\[
\begin{align*}
eqn 1 = 2x + y -z = 3 \\
eqn 2 =  y - 11z = -9 \\
eqn3 = -72z = -72 \\
\end{align*}
\]

Now you can find *Z* and solve the rest of the equations! This is now in what is said to be upper triangular, also known as **ROW echelon form** 



<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

**There are some rules in Gaussian Elimination**

* As you saw, you must operate on the right hand side and left hand side at the same time. Whatever you apply to on side of your equation, has to happen on the other side too. For example multiplications.
* The matrix has to square
* Rows can be replaced with a sum/ combination of rows
* work on one column at a time, choosing a pivot and eliminating all other non zero values below it.
* switch rows to avoid zeros on the diagonal (pivoting)
* if swapping rows does not work and there are sill zeros on the diagonal,  - this indicates a SINGULAR matrix (see https://study.com/learn/lesson/singular-matrix-properties-examples.html#:~:text=A%20singular%20matrix%20is%20a,does%20not%20have%20an%20inverse.)

The computational cost of Gauss Elimination is O(n^3) - it is not efficient for large numbers of equations.

#### Back to our drug discovery problem!

In [228]:
import numpy as np

# we have turned our equations into matrices in the form A(x) = b
# our square matrix is in the form 4x4

A = np.array([[2, 3, 1.5, 0.5, 2],
              [1, 2, 2.5, 1.5, 1],
              [2.5, 1, 3, 2, 2.5],
              [1.5, 7, 1, 3, 1.5],
              [2, 1.5, 2, 1, 3]])

b = np.array([10, -5, 7, -6, 3])  # Replace E1-E4 with actual experimental outcomes.


In [218]:
import numpy as np
import sys

# this cell creates random matrices for use with the 
# functions for Gauss Elimination should you want to try

def random_non_singular_A_matrix(n):
    """creates a random non singular matrix
    while loop ensures condition number is below threshold"""
    
    if n == 0:  # Added check for n == 0 to address the case of creating an array with zero size.
        print("You can't have a zero value, enter different value")
        return None, None  
    A = np.random.rand(n, n)
    while np.linalg.cond(A) > 1/ sys.float_info.epsilon:
        A = np.random.rand(n,n)
    return A


def random_b_matrix(n):
    R = np.random.rand(n, n)
    A = np.zeros((n, n))
    triu = np.triu_indices(n)
    A[triu] = R[triu]
    return A


In [285]:
import numpy as np

# step 1 - elimination with Gauss Elimination 

# During the first iteration (k = 0) of the outer loop, k, k would be 0, 0
# This means that we are considering the pivot element in the first row and the first column
# Subsequent iterations of the outer loop will update k to consider the pivot element in subsequent rows and columns


def gaussian_elimation(a, b):
    n = len(a) # setting the length of the matrix as n in our case '5'
    for k in range (n-1):  # k is the index of pivot row (loop for start of row to end) (index 0,0)
        for i in range(k+1, n): # row below pivot row (new row)
            if a[i, k] == 0: continue  # if already zero, move onto next row
            factor = a[k, k]/ a[i, k] # dividing current element by pivot to find the factor as before 
            for j in range(k, n): 
                a[i, j] = a[k, j] - a[i, j] * factor # finding value by multiplying factor and taking away as we did before!
            b[i] = b[i] - factor * b[k] # b vector new value calculated as above
            
    return a, b

# back substituing to solve the rest of the equations!

def back_substitution(a, b):
    n = len(b)
    x = np.zeros(n, float) # empty array to store the values
    x[n-1] = b[n-1] / a[n-1, n-1] # solving bottom up (hence index n-1)
    for i in range(n-2, -1, -1): # loop, moving up by 1 each time
        sum_ax = 0
        for j in range (i+1, n):
            sum_ax += a[i,j] * x[j]
        x[i] = (b[i]- sum_ax) / a[i, i]

    return (x)




In [286]:
import numpy as np
import scipy.linalg


# Original matrices
A = np.array([[2, 3, 1.5, 0.5],
              [1, 2, 2.5, 1.5],
              [2.5, 1, 3, 2],
              [1.5, 7, 1, 3]])
b = np.array([10, -5, 7, -6])

# Make copies of A and b for implementation
A_copy = np.copy(A)
b_copy = np.copy(b)

# Use the copies for your Gaussian elimination and back substitution
A_mod, b_mod = gaussian_elimation(A_copy, b_copy)
x = back_substitution(A_mod, b_mod)

# Use the original A and b for scipy's solve function
x_scipy = scipy.linalg.solve(A, b)

print(f"These are your results: \n{x}")
print(f"These are scipy's results: \n{x_scipy}")

# Check if the results are almost equal (they are not!)
np.testing.assert_almost_equal(x_scipy, x)


These are your results: 
[-18.63075769  14.47696924   2.15750188   1.18870968]
These are scipy's results: 
[ 9.50967742 -0.96129032 -2.90967742 -3.54193548]


AssertionError: 
Arrays are not almost equal to 7 decimals

Mismatched elements: 4 / 4 (100%)
Max absolute difference: 28.14043511
Max relative difference: 3.97964722
 x: array([ 9.5096774, -0.9612903, -2.9096774, -3.5419355])
 y: array([-18.6307577,  14.4769692,   2.1575019,   1.1887097])

### There is a problem with this code!
### it is unable to swap rows and so therefore cannot pick the best pivot and hence we might receive the wrong answer for some matrices. Let's add the ability to do partial pivoting where neccessary!

it is called partial because the columns do not change, only the rows.

Without row swapping (partial pivoting), the algorithm may encounter situations where division by zero occurs or where numerical inaccuracies lead to incorrect results, particularly when dealing with ill-conditioned matrices or matrices with very small or very large elements


In [287]:
import numpy as np

# step 1 - elimination this time with partial pivotting 

def gaussian_elimation_pivot(a, b):
    n = len(a)  
    k = 0 # pivot row

    for k in range(n-1):
        # Partial pivoting (finding the largest number in the column)
        max_index = np.argmax(np.abs(a[k:n, k])) + k
        # Swap rows in 'a'
        a[[k, max_index], :] = a[[max_index, k], :]
        # Swap elements in 'b'
        b[[k, max_index]] = b[[max_index, k]]

        # now you have a rearranged matrix!

        for i in range(k+1, n):
            factor = a[i, k] / a[k, k]
            for j in range(k, n):  # Iterate over columns from k to the end
                # Update the elements in row 'i' based on the factor
                a[i, j] = a[i, j] - factor * a[k, j]
            b[i] = b[i] - factor * b[k]       
    
    return a, b

def back_substitution_pivot(a, b):
    n = len(b)
    x = np.zeros(n, float)
    x[n-1] = b[n-1] / a[n-1, n-1]
    for i in range(n-2, -1, -1):
        sum_ax = 0
        for j in range (i+1, n):
            sum_ax += a[i,j] * x[j]
        x[i] = (b[i]- sum_ax) / a[i, i]

    return (x)




In [288]:
import numpy as np
import scipy.linalg

# Make sure to define your gaussian_elimation and back_substitution functions correctly.

# Original matrices
A = np.array([[2, 3, 1.5, 0.5],
              [1, 2, 2.5, 1.5],
              [2.5, 1, 3, 2],
              [1.5, 7, 1, 3]])
b = np.array([10, -5, 7, -6])

# Make copies of A and b for your implementation
A_copy = np.copy(A)
b_copy = np.copy(b)

# Use the copies for your Gaussian elimination and back substitution
A_mod, b_mod = gaussian_elimation_pivot(A_copy, b_copy)
x = back_substitution_pivot(A_mod, b_mod)

# Use the original A and b for scipy's solve function
x_scipy = scipy.linalg.solve(A, b)

print(f"These are your results: \n{x}")
print(f"These are scipy's results: \n{x_scipy}")

# Check if the results are almost equal
np.testing.assert_almost_equal(x_scipy, x)



These are your results: 
[ 8.2422043  -0.96034946 -2.15053763 -3.09677419]
These are scipy's results: 
[ 9.50967742 -0.96129032 -2.90967742 -3.54193548]


There is still a difference between some of our answers versus that of scipy - why might this be?

It could be due to the **condition** number of our matrix. The conditon number of a matrix is a measure of how close a matrix is to being singular - a small change results in zeros in the pivot positions. Even if not exactly zero, a pivot value close to zero can lead to large differences in the final result. This is when a matrix can be called nearly singular or ill conditioned. We can calculate the condition of a matrix using numpy. 

lets calculate it for our matrix.

In [290]:
import numpy as np

A = np.array([[2, 3, 1.5, 0.5],
              [1, 2, 2.5, 1.5],
              [2.5, 1, 3, 2],
              [1.5, 7, 1, 3]])

cond_number = np.linalg.cond(A)
print("Condition number of A:", cond_number)

Condition number of A: 12.177123238741279


# Let's try some other matrices. 
## Generating a random nxn matrix with for our function
### we will create matrices with better condition numbers than 12. If the conditon number is more than 1, it is rejected until a matrix with a condition <1 is found!

In [291]:
def random_non_singular_matrix(n):
    A = np.random.rand(n, n)
    while np.linalg.cond(A) > 1/sys.float_info.epsilon:
        A = np.random.rand(n, n)
    return A

In [292]:
As =[np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]]),
    random_non_singular_matrix(3),
    random_non_singular_matrix(4),
    random_non_singular_matrix(5),
    random_non_singular_matrix(6)
]

In [293]:
bs = [
    np.array([1, 2, 3]),
    np.random.rand(3),
    np.random.rand(4),
    np.random.rand(5),
    np.random.rand(6),
]

In [294]:
import numpy as np
import scipy.linalg

for A, b in zip(As, bs):
    # Make copies of A and b to avoid modifying the originals if necessary
    A_copy = np.copy(A)
    b_copy = np.copy(b)

    A_mod, b_mod = gaussian_elimation_pivot(A_copy, b_copy)
    x_mine = back_substitution_pivot(A_mod, b_mod)
    print(f"this is mine \n {x_mine}")

    x_scipy = scipy.linalg.solve(A, b)  # Use the original A and b here
    print(f"this is scipy  \n {x_scipy}")

    # Assert that the solutions are almost equal for each pair
    np.testing.assert_almost_equal(x_scipy, x_mine)


this is mine 
 [1. 2. 3.]
this is scipy  
 [1. 2. 3.]
this is mine 
 [-0.27493958  1.12491077  1.05514902]
this is scipy  
 [-0.27493958  1.12491077  1.05514902]
this is mine 
 [-1.08330752 -0.22087329  2.42231592  1.29333119]
this is scipy  
 [-1.08330752 -0.22087329  2.42231592  1.29333119]
this is mine 
 [ 0.34656994  2.07416929 -0.19929566 -1.19434694 -0.43690885]
this is scipy  
 [ 0.34656994  2.07416929 -0.19929566 -1.19434694 -0.43690885]
this is mine 
 [ 1.50519771 -1.18334257  1.50624964 -0.57975219 -0.97698062  0.76911736]
this is scipy  
 [ 1.50519771 -1.18334257  1.50624964 -0.57975219 -0.97698062  0.76911736]


I hope this was helpful in your learning of Gauss Elimination. There are of course more efficient algorithms, but it is a great starting point to learn about linear algebra and the associated algorithms